name = "donut"
version = "1.0.0"
target = "javascript"

description = "An elegant Lustre package for interacting with and simulating websockets."
licenses = ["MIT"]
repository = { type = "github", user = "MamounKolovos", repo = "donut" }

links = [
  { title = "Lustre", href = "https://hexdocs.pm/lustre/" },
]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
lustre = ">= 5.7.1 and < 6.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.6 and < 3.0.0"

[tools.lustre.dev]
watch = ["./dev"]